Update raspi-backup

diff --git a/raspi-backup b/raspi-backup
--- a/raspi-backup
+++ b/raspi-backup
@@ -1,6 +1,7 @@
 #!/bin/bash
 BACKUP_PATH='/root'
 IMAGE_FREESPACE=64
+MOUNT_PATH=/mnt
 
 function delete_lo()
 {
@@ -43,6 +44,52 @@ function setup_lo()
     partx -a ${IMAGE_LOOP}
     if [ $? -ne 0 ]; then
         echo "Failed to create loop device for partitions."
+        exit 1
+    fi
+}
+
+function mount_image()
+{
+    if [ ! -d ${MOUNT_PATH} ]; then
+        mkdir -p ${MOUNT_PATH}
+    fi
+    
+    mount ${IMAGE_LOOP}p2 ${MOUNT_PATH}
+    if [ $? -ne 0 ]; then
+        echo "Error mounting root partition"
+        delete_lo
+        exit 1
+    fi
+    
+    if [ ! -d ${MOUNT_PATH}/boot ]; then
+        mkdir -p ${MOUNT_PATH}/boot
+    fi
+    
+    mount ${IMAGE_LOOP}p1 ${MOUNT_PATH}/boot
+    if [ $? -ne 0 ]; then
+        echo "Error mounting boot partition"
+        umount -l ${MOUNT_PATH}
+        delete_lo
+        exit 1
+    fi
+}
+
+function unmount_image()
+{
+    umount ${MOUNT_PATH}/boot
+    if [ $? -ne 0 ]; then
+        echo "Error unmounting boot partition."
+        umount -l ${MOUNT_PATH}/boot
+        umount -l ${MOUNT_PATH}
+        delete_lo
+        exit 1
+    fi
+    
+    umount ${MOUNT_PATH}
+    if [ $? -ne 0 ]; then
+        echo "Error unmounting root partition."
+        umount -l ${MOUNT_PATH}
+        delete_lo
         exit 1
     fi
 }
@@ -134,6 +181,19 @@ function create_image()
         exit 1
     fi
     
+    mount_image
+    
+    mkdir ${MOUNT_PATH}/dev {MOUNT_PATH}/media ${MOUNT_PATH}/mnt ${MOUNT_PATH}/proc ${MOUNT_PATH}/run ${MOUNT_PATH}/sys ${MOUNT_PATH}/tmp
+    if [ $? -ne 0 ]; then
+        echo "Error creating directories."
+        unmount_image
+        delete_lo
+        exit 1
+    fi
+    
+    chmod a+rwxt ${MOUNT_PATH}/tmp
+    
+    unmount_image
     delete_lo
 }
 
